### ISSUE TITLE
Add resources around agile-coretime 

### ISSUE THREAD

**Issue by kianenigma** [haquefardeen/awesome-dot#24]
- https://polkadot-public.notion.site/Agile-Coretime-FAQ-c930796e8c884011adb1fa24ef22f77c#2007eb68754a48beadaf8b76fbfe60b8
- https://lastic.xyz/
- regionX-Labs

and more please :)

**Comment by haquefardeen** [comment]
These resources were added in #28, thank you for sending this over ser!
